### ISSUE TITLE
Unable to build on Ubuntu 24.04

### ISSUE THREAD

**Issue by jhonny-oliveira** [Secretchronicles/TSC#710]
Hi!

I'm having trouble building the game on Ubuntu 24.04:

```
error: ‘sort’ is not a member of ‘std’; did you mean ‘qsort’?
```
You can find attached the complete build log: [tsc_2.1.0-1xtradeb1.2404.1_build_log.txt](https://github.com/Secretchronicles/TSC/files/15022772/tsc_2.1.0-1xtradeb1.2404.1_build_log.txt).

Thank you!
Jhonny Oliveira
https://xtradeb.net

**Comment by xet7** [comment]
@jhonny-oliveira 

I added some .deb packages for Ubuntu 24.04 and Debian 12 to downloads page:

http://secretchronicles.org/en/download/

**Comment by jhonny-oliveira** [comment]
Dear @xet7 ,

can you please let me know what was the fix? I need to build the package on my own.

Thank you!

**Comment by xet7** [comment]
@jhonny-oliveira 

I did not fix anything. I did just build package same way like before. A moment ago, I wrote building .deb packages info here:

https://github.com/Secretchronicles/TSC/wiki/Building-.deb-packages

**Comment by jhonny-oliveira** [comment]
Ok!

I found the problem. I'm building from the released source and you are building from git latest. I was missing two commits (1a011c8 and f5760d1). I also took the opportunity to update to pod-parser git commit 98f8c94.

I would be nice if you could make a release for pod-parser. Ideally, launchpad.net builds should always come from properly tagged and released source and the pod-parser repo used in this case, doesn't have any release/tag.

Thank you!

**Comment by xet7** [comment]
@jhonny-oliveira 

I added releases:
- https://github.com/Secretchronicles/pod-parser/releases/tag/1.0
- https://github.com/Secretchronicles/tinyclipboard/releases/tag/1.0

Is it now OK ?

**Comment by jhonny-oliveira** [comment]
Perfect! Thank you!
