### ISSUE TITLE
Freetype 2.6.2 breaks CEGUI 0.7.x

### ISSUE THREAD

**Issue by Quintus** [Secretchronicles/TSC#500]
Hi everyone,

I found out that versions of the Freetype library >= 2.6.2 are incompatible with CEGUI 0.7.9. Trying to start TSC linked against freetype 2.6.2 (and probably newer) will result in the game only showing a black screen. Interrupting it and inspecting with GDB yields this stacktrace:

~~~~
% gdb ./TESTINSTALL/bin/tsc 
GNU gdb (GDB) 7.10.1
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./TESTINSTALL/bin/tsc...done.
(gdb) r
Starting program: /home/quintus/repos/privat/projekte/c++/TSC/tsc/build/TESTINSTALL/bin/tsc 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Initializing resource manager and core classes
Game data directory: /home/quintus/repos/privat/projekte/c++/TSC/tsc/build/TESTINSTALL/share/tsc
User data directory: /home/quintus/.local/share/tsc
User cache directory: /home/quintus/.cache/tsc
User config directory: /home/quintus/.config/tsc
Initializing Package Manager
Configuration file is '/home/quintus/.config/tsc/config.xml'.
Translation locale is de_DE.UTF-8
Translation support with gettext set to:
	Directory /home/quintus/repos/privat/projekte/c++/TSC/tsc/build/TESTINSTALL/share/tsc/translations
	Codeset: UTF-8
	Text domain: Secretchronicles
[New Thread 0x7fffe7440700 (LWP 24938)]
[Thread 0x7fffe7440700 (LWP 24938) exited]
[New Thread 0x7fffe7440700 (LWP 24939)]
CEGUI log file is at '/home/quintus/.cache/tsc/cegui.log'.
^C
Program received signal SIGINT, Interrupt.
0x00007ffff46b9910 in ft_mem_free@plt () from /usr/lib/libfreetype.so.6
(gdb) bt
#0  0x00007ffff46b9910 in ft_mem_free@plt () from /usr/lib/libfreetype.so.6
#1  0x00007ffff46c5144 in FT_List_Finalize () from /usr/lib/libfreetype.so.6
#2  0x00007ffff46db6f1 in ?? () from /usr/lib/libfreetype.so.6
#3  0x00007ffff46c285b in FT_Load_Glyph () from /usr/lib/libfreetype.so.6
#4  0x00007ffff470aa48 in ?? () from /usr/lib/libfreetype.so.6
#5  0x00007ffff46c2a6d in FT_Load_Glyph () from /usr/lib/libfreetype.so.6
#6  0x0000000000924bda in CEGUI::FreeTypeFont::updateFont (this=this@entry=0x1094ff0) at CEGUIFreeTypeFont.cpp:447
#7  0x000000000092538d in CEGUI::FreeTypeFont::FreeTypeFont (this=0x1094ff0, font_name=..., point_size=13, anti_aliased=<optimized out>, font_filename=..., resource_group=..., auto_scaled=<optimized out>, 
    native_horz_res=<optimized out>, native_vert_res=<optimized out>, specific_line_spacing=0) at CEGUIFreeTypeFont.cpp:87
#8  0x000000000081c616 in CEGUI::Font_xmlHandler::createFreeTypeFont (this=this@entry=0x7fffffffbab0, attributes=...) at CEGUIFont_xmlHandler.cpp:202
#9  0x000000000081d5bb in CEGUI::Font_xmlHandler::elementFontStart (this=this@entry=0x7fffffffbab0, attributes=...) at CEGUIFont_xmlHandler.cpp:141
#10 0x000000000081d87b in CEGUI::Font_xmlHandler::elementStart (this=0x7fffffffbab0, element=..., attributes=...) at CEGUIFont_xmlHandler.cpp:113
#11 0x000000000098f42f in CEGUI::processXMLElement (handler=..., node=0x10638b0) at CEGUILibxmlParser.cpp:59
#12 0x000000000098fef5 in CEGUI::LibxmlParser::parseXMLFile (this=<optimized out>, handler=..., filename=..., resourceGroup=...) at CEGUILibxmlParser.cpp:121
#13 0x000000000081b591 in CEGUI::Font_xmlHandler::Font_xmlHandler (this=0x7fffffffbab0, filename=..., resource_group=...) at CEGUIFont_xmlHandler.cpp:76
#14 0x000000000083423e in CEGUI::NamedXMLResourceManager<CEGUI::Font, CEGUI::Font_xmlHandler>::create (action=CEGUI::XREA_RETURN, resource_group=..., xml_filename=..., this=0x106a0b0)
    at ../../cegui/include/CEGUINamedXMLResourceManager.h:229
#15 CEGUI::Scheme::loadFonts (this=this@entry=0x1084240) at CEGUIScheme.cpp:234
#16 0x000000000083547b in CEGUI::Scheme::loadResources (this=0x1084240) at CEGUIScheme.cpp:106
#17 0x000000000078d0f7 in CEGUI::NamedXMLResourceManager<CEGUI::Scheme, CEGUI::Scheme_xmlHandler>::doExistingObjectAction (this=0x1084a40, object_name=..., object=0x1084240, action=CEGUI::XREA_RETURN)
    at /home/quintus/repos/privat/projekte/c++/TSC/tsc/build/cegui/include/CEGUI/CEGUINamedXMLResourceManager.h:359
#18 0x000000000078c4a4 in CEGUI::NamedXMLResourceManager<CEGUI::Scheme, CEGUI::Scheme_xmlHandler>::create (this=0x1084a40, xml_filename=..., resource_group=..., action=CEGUI::XREA_RETURN)
    at /home/quintus/repos/privat/projekte/c++/TSC/tsc/build/cegui/include/CEGUI/CEGUINamedXMLResourceManager.h:231
#19 0x0000000000783924 in TSC::cVideo::Init_CEGUI_Data (this=0xdc9b20) at /home/quintus/repos/privat/projekte/c++/TSC/tsc/src/video/video.cpp:149
#20 0x00000000007b615d in TSC::Init_Game () at /home/quintus/repos/privat/projekte/c++/TSC/tsc/src/core/main.cpp:275
#21 0x00000000007b5823 in main (argc=1, argv=0x7fffffffe878) at /home/quintus/repos/privat/projekte/c++/TSC/tsc/src/core/main.cpp:180
(gdb) q
A debugging session is active.

	Inferior 1 [process 24934] will be killed.

Quit anyway? (y or n) y
~~~~

It appears CEGUI locks itself in an endless loop while trying to read a TTF font file.

I have no easy solution for this. Since all other programs work fine with freetype 2.6.2 it probably is not a bug in freetype, but a wrong use of it by CEGUI. The correct solution thus is to upgrade CEGUI to a newer version that hopefully has fixed that.

In the meantime, please ensure you have freetype installed in a version < 2.6.2. Version 2.6.1 works as expected. If you use ArchLinux, simply downgrade your freetype package from your local package cache:

~~~~
pacman -U /var/cache/pacman/pkg/freetype2-2.6.1-1-*.pkg.tar.xz
~~~~

This is only a workaround. We need to upgrade CEGUI or move away from it.

Valete,
Quintus

**Comment by Quintus** [comment]
The stacktrace has been made with current tip of `devel`, i.e. commit 3cf40a1179828dfd2731d3c5d0a7d75ab1ae4b7c.

Valete,
Quintus

**Comment by Quintus** [comment]
Using my example program at https://github.com/Quintus/sfml-gui-test I can confirm that CEGUI 0.8.5 (current CEGUI development version) works with Freetype 2.6.2 as it should. This issue is thus resolvable by upgrading CEGUI.

Valete,
Quintus

**Comment by Boiethios** [comment]
I have the 0.8.7 version of libcegui-mk2 (I think this is the library you are talking about) with libfreetype 2.6.3 on Debian, and it still crashes with blackscreen.

**Comment by Quintus** [comment]
Boiethios <notifications@github.com> writes:

> I have the 0.8.7 version of libcegui-mk2 (I think this is the library
> you are talking about) with libfreetype 2.6.3 on Debian, and it still
> crashes with blackscreen.

This is impossible, because TSC 2.0.0 cannot be built with CEGUI 0.8.x
(the build will abort with compilation errors). There must be a 0.7.x
CEGUI flying around somewhere on your computer. The only version of TSC
that builds against CEGUI 0.8.x is the head of the feature-cegui-0.8
branch, which is a development version.

If you still have this issue with the code in feature-cegui-0.8, then it
is something new indeed. Can you test that?

FYI: CEGUI 0.8.0 was a major release of CEGUI breaking lots of its API.

Vale,
Quintus

-- 
Blog: http://www.guelkerdev.de
GPG-Schlüssel: F1D8799FBCC8BC4F

**Comment by Boiethios** [comment]
Oh you were right, there was a 0.7.x version in the sources I downloaded.

**Comment by Quintus** [comment]
This issue was resolved by upgrading to CEGUI 0.8.x with commit 58a5440a02679e9b2be6be0f624911d5b235a04d.

Valete,
Quintus
